// <auto-generated />
using System;
using BIBData.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BIBData.Migrations
{
    [DbContext(typeof(BIBDbContext))]
    partial class BIBDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BIBData.Models.Lener", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Familienaam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Geboortedatum")
                        .HasColumnType("datetime2");

                    b.Property<string>("Telefoonnr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Voornaam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Leners");
                });

            modelBuilder.Entity("BIBData.Models.OperatingSysteem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Operatingsystemen");
                });

            modelBuilder.Entity("BIBData.Models.Reservering", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("GereserveerdOp")
                        .HasColumnType("datetime2");

                    b.Property<int>("LenerId")
                        .HasColumnType("int");

                    b.Property<int>("UitleenobjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LenerId");

                    b.HasIndex("UitleenobjectId");

                    b.ToTable("Reserveringen");
                });

            modelBuilder.Entity("BIBData.Models.Uitleenobject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Jaar")
                        .HasColumnType("int");

                    b.Property<decimal>("Kostprijs")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Uitleenobjecten");

                    b.HasDiscriminator().HasValue("Uitleenobject");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("BIBData.Models.Uitlening", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LenerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Tot")
                        .HasColumnType("datetime2");

                    b.Property<int>("UitleenobjectId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Van")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LenerId");

                    b.HasIndex("UitleenobjectId");

                    b.ToTable("Uitleningen");
                });

            modelBuilder.Entity("BIBData.Models.Boek", b =>
                {
                    b.HasBaseType("BIBData.Models.Uitleenobject");

                    b.Property<int>("Aantalpaginas")
                        .HasColumnType("int");

                    b.Property<string>("Auteur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Boek");
                });

            modelBuilder.Entity("BIBData.Models.Device", b =>
                {
                    b.HasBaseType("BIBData.Models.Uitleenobject");

                    b.Property<int>("OperatingSysteemId")
                        .HasColumnType("int");

                    b.Property<float>("Schermgrootte")
                        .HasColumnType("real");

                    b.HasIndex("OperatingSysteemId");

                    b.HasDiscriminator().HasValue("Device");
                });

            modelBuilder.Entity("BIBData.Models.Reservering", b =>
                {
                    b.HasOne("BIBData.Models.Lener", "Lener")
                        .WithMany()
                        .HasForeignKey("LenerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BIBData.Models.Uitleenobject", "Uitleenobject")
                        .WithMany()
                        .HasForeignKey("UitleenobjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lener");

                    b.Navigation("Uitleenobject");
                });

            modelBuilder.Entity("BIBData.Models.Uitlening", b =>
                {
                    b.HasOne("BIBData.Models.Lener", "Lener")
                        .WithMany("Uitleningen")
                        .HasForeignKey("LenerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BIBData.Models.Uitleenobject", "Uitleenobject")
                        .WithMany()
                        .HasForeignKey("UitleenobjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lener");

                    b.Navigation("Uitleenobject");
                });

            modelBuilder.Entity("BIBData.Models.Device", b =>
                {
                    b.HasOne("BIBData.Models.OperatingSysteem", "OperatingSysteem")
                        .WithMany()
                        .HasForeignKey("OperatingSysteemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OperatingSysteem");
                });

            modelBuilder.Entity("BIBData.Models.Lener", b =>
                {
                    b.Navigation("Uitleningen");
                });
#pragma warning restore 612, 618
        }
    }
}
